server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imitation_12306_ci?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
      password: 123456
      timeout: 10000
  cache:
    type: redis

my:
  jwt:
    issuer: my-local-issuer
    secret: EHnbNd1KxkXceo9v
    expire: 720
    aheadAutoRefresh: 60
  common:
    httpsEnabled: false
    baseDomainName: org.infinity
    limitRate: false
    webhookUserName: kJ_4LPrrT5W3wVMK_RhzMA
    webhookPassword: qW-2S-9fTs26MnGigO0mTw
  redis:
    domainEventStream: DomainEvent.LOCAL
    notificationStream: Notification.LOCAL
    webhookStream: Webhook.LOCAL


