server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/i12306_ci_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      database: 3
      host: localhost
      port: 6379
      password: 123456
      timeout: 10000
  cache:
    type: redis

mybatis-plus:
  type-aliases-package: org.infinity.core.*.model.po
  global-config:
    db-config:
      id-type: auto
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

my:
  jwt:
    issuer: my-local-issuer
    secret: EHnbNd1KxkXceo9v
    expire: 720
    aheadAutoRefresh: 60
  common:
    httpsEnabled: false
    baseDomainName: org.infinity
    limitRate: false
  redis:
    domainEventStream: DomainEvent.LOCAL
    notificationStream: Notification.LOCAL
    webhookStream: Webhook.LOCAL
